# -*- coding: utf-8 -*-
"""Lab1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CLn4i2qGCzTg8y_lRVkx1JCFPOA_6SLt

Работа 1
"""

!pip install tensorflow
!pip install keras
!pip install matplotlib
!pip install numpy

import math

a = 5
b = 2
print(a + b)
print(a - b)
print(a * b)
print(a / b)

a = 5
b = 2
print(a > b)
print(a < b)
print(a == b)
print(a != b)

print("Hello, my name Nikita")
x = input("Введите число: ")
print("Вы ввели число " + x)