# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14vnuR7jsnXtf6WPp6EkmFmWvRdv6aBNx
"""

!pip install tensorflow
!pip install tf-nightly
!pip install keras

import numpy as np
import matplotlib.pyplot as pit
from tensorflow import keras
from google.colab import files
from io import BytesIO
from PIL import Image

model = keras.applications.VGG16()

!pip install matplotlib

import math

import matplotlib.pyplot as plt

uploaded = files.upload()

img = Image.open(BytesIO(uploaded[list(uploaded.keys())[0]]))
plt.imshow( img )

img = np.array(img)
x = keras.applications.vgg16.preprocess_input(img)
print(x.shape)
x = np.expand_dims(x, axis=0)

res = model.predict( x )
print(np.argmax(res))